### ISSUE TITLE
Won't compile under OpenCv 3.3

### ISSUE THREAD

**Issue by pbertoni89** [SimoneAlbertini/GMM-Clustering#1]
Because `EM` class is now under `cv::ml::EM`, not `cv::EM`

**Comment by SimoneAlbertini** [comment]
Thank you for noticing the issue.
The code was actually written for OpenCV 2.2 (at the time of my phd) so I
did not expect it would work in the next major releases.

If it is just that easy to make it work for the new version of OpenCV I
will just add a note in the readme.
Notice that I no longer maintain this "projects so I will not update the
code, leaving it as it is: designed for previous versions of the library.

Thank you for using my code.

2017-08-11 15:55 GMT+02:00 Patrizio Bertoni <notifications@github.com>:
